import jsPDF from 'jspdf'
import type { CutListSummary } from './cutListCalculator'
import type { OuterBox } from '../stores/furnitureStore'

export function exportCutListPdf(
  designName: string,
  furnitureType: string,
  outerBox: OuterBox,
  summary: CutListSummary,
) {
  const doc  = new jsPDF({ unit: 'mm', format: 'a4' })
  const pw   = 210   // page width
  const lm   = 15    // left margin
  const rm   = 15    // right margin
  const cw   = pw - lm - rm  // content width

  let y = 20

  const line = () => {
    doc.setDrawColor(220, 220, 220)
    doc.setLineWidth(0.3)
    doc.line(lm, y, pw - rm, y)
    y += 4
  }

  // ── Header ──────────────────────────────────────────────────────────────

  doc.setFontSize(18)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(30, 30, 30)
  doc.text('Cut List', lm, y)

  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(100, 100, 100)
  doc.text(new Date().toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' }), pw - rm, y, { align: 'right' })

  y += 7

  doc.setFontSize(13)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(30, 30, 30)
  doc.text(designName, lm, y)

  y += 5
  doc.setFontSize(9)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(120, 120, 120)
  doc.text(
    `${furnitureType}  ·  ${outerBox.width} × ${outerBox.height} × ${outerBox.depth} mm  ·  ${summary.totalPieces} pieces`,
    lm, y,
  )

  y += 5
  line()

  // ── Groups ───────────────────────────────────────────────────────────────

  const COL = {
    name: lm,
    len:  lm + cw * 0.42,
    wid:  lm + cw * 0.54,
    thk:  lm + cw * 0.66,
    qty:  lm + cw * 0.78,
    note: lm + cw * 0.86,
  }

  const tableHeader = () => {
    doc.setFontSize(7.5)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(140, 140, 140)
    doc.text('Panel',     COL.name, y)
    doc.text('Length',    COL.len,  y)
    doc.text('Width',     COL.wid,  y)
    doc.text('Thickness', COL.thk,  y)
    doc.text('Qty',       COL.qty,  y)
    y += 4
    doc.setDrawColor(200, 200, 200)
    doc.setLineWidth(0.2)
    doc.line(lm, y, pw - rm, y)
    y += 3
  }

  summary.groups.forEach((group) => {
    // Page break check
    if (y > 260) { doc.addPage(); y = 20 }

    // Group heading
    doc.setFontSize(9)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(50, 50, 50)
    doc.text(group.label.toUpperCase(), lm, y)
    y += 5

    tableHeader()

    group.items.forEach((item, idx) => {
      if (y > 265) { doc.addPage(); y = 20; tableHeader() }

      // Alternating row bg
      if (idx % 2 === 0) {
        doc.setFillColor(248, 248, 248)
        doc.rect(lm, y - 3.5, cw, 6, 'F')
      }

      doc.setFontSize(9)
      doc.setFont('helvetica', 'normal')
      doc.setTextColor(40, 40, 40)
      doc.text(item.name,                COL.name, y)

      doc.setTextColor(60, 60, 60)
      doc.text(`${item.length} mm`,      COL.len,  y)
      doc.text(`${item.width} mm`,       COL.wid,  y)
      doc.text(`${item.thickness} mm`,   COL.thk,  y)

      doc.setFont('helvetica', 'bold')
      doc.setTextColor(40, 40, 40)
      doc.text(`${item.qty}`,            COL.qty,  y)
      doc.setFont('helvetica', 'normal')

      y += 6
    })

    y += 4
  })

  // ── Summary footer ────────────────────────────────────────────────────

  if (y > 255) { doc.addPage(); y = 20 }

  line()
  doc.setFontSize(9)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(40, 40, 40)
  doc.text(`Total pieces: ${summary.totalPieces}`, lm, y)
  doc.text(
    `Total board area: ${summary.totalAreaM2.toFixed(2)} m²`,
    pw - rm, y, { align: 'right' },
  )

  y += 6
  doc.setFontSize(7.5)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(160, 160, 160)
  doc.text('Generated by HouseXpert · Furniture Designer', lm, y)

  // ── Save ──────────────────────────────────────────────────────────────

  const safeName = designName.replace(/[^a-z0-9]/gi, '_').toLowerCase()
  doc.save(`${safeName}_cut_list.pdf`)
}
